---
version: '3'

includes:
  # Include here the reusable pieces of 'tasks', to avoid DRY.
  common:
    taskfile: './DX/taskfile/Taskfile.common.yml'
    dir: ./DX/taskfile

tasks:
    docs:
        cmds:
            - ./DX/scripts/generate-terraform-docs.sh --dir=terraform/taggy/omd

    default:
        cmds:
            - task: 'common:default'
