---
version: '3'

includes:
  # Include here the reusable pieces of 'tasks', to avoid DRY.
  common:
    taskfile: './DX/taskfile/Taskfile.common.yml'

  enforcer:
    taskfile: './terraform/examples/Taskfile.enforcer.yml'
    dir: ./terraform/examples/omd

  aws:
    taskfile: './terraform/examples/Taskfile.aws.yml'
    dir: ./terraform/examples/aws

tasks:
    docs:
        cmds:
            - ./DX/scripts/generate-terraform-docs.sh --dir=terraform/taggy/modules/omd
            - ./DX/scripts/generate-terraform-docs.sh --dir=terraform/taggy/modules/cloud

    default:
        cmds:
            - task: 'common:default'

    enforcer-recipes-basics:
        cmds:
            - task: 'enforcer:recipe-pass'
            - task: 'enforcer:recipe-fail-enforced-tag-failed'
            - task: 'enforcer:recipe-fail-tag-key-with-empty-values'
            - task: 'enforcer:recipe-fail-tag-value-non-trimmed'

    aws-recipes-basics:
        cmds:
            - task: 'aws:recipe-pass'
            - task: 'aws:recipe-fail-invalid-aws-prefix'
            - task: 'aws:recipe-fail-max-key-length-reached'
