---
version: '3'

includes:
  # Include here the reusable pieces of 'tasks', to avoid DRY.
  common:
    taskfile: './DX/taskfile/Taskfile.common.yml'
    dir: ./DX/taskfile

tasks:
    docs:
        cmds:
            - ./DX/scripts/generate-terraform-docs.sh # TODO: make it generic, and able to receive an argument to set the working_dir by the caller script.

    default:
        cmds:
            - task: 'common:default'
