---
version: '3'

includes:
  # Include here the reusable pieces of 'tasks', to avoid DRY.
  common:
    taskfile: './DX/taskfile/Taskfile.common.yml'

  omd:
    taskfile: './terraform/examples/Taskfile.yml'
    dir: ./terraform/examples/omd

tasks:
    docs:
        cmds:
            - ./DX/scripts/generate-terraform-docs.sh --dir=terraform/taggy/omd

    default:
        cmds:
            - task: 'common:default'

    plan-enforcer:
        cmds:
            - task: 'omd:init'
