---
version: '3'

includes:
  # Include here the reusable pieces of 'tasks', to avoid DRY.
  common:
    taskfile: './DX/taskfile/Taskfile.common.yml'

  omd:
    taskfile: './terraform/examples/Taskfile.yml'
    dir: ./terraform/examples/omd

tasks:
    docs:
        cmds:
            - ./DX/scripts/generate-terraform-docs.sh --dir=terraform/taggy/omd

    default:
        cmds:
            - task: 'common:default'

    omd-enforcer-recipes-basics:
        cmds:
            - task: 'omd:recipe-pass'
            - task: 'omd:recipe-fail-enforced-tag-failed'
              ignore_error: true
            - task: 'omd:recipe-fail-tag-key-with-empty-values'
              ignore_error: true
            - task: 'omd:recipe-fail-tag-value-non-trimmed'
              ignore_error: true
