---
version: '3'

vars:
    RECIPE_MODULE_OMD_ENFORCER: "enforcer"
    RECIPE_MODULE_AWS: "aws"

includes:
    tf:
        taskfile: './../../DX/taskfile/Taskfile.terraform.yml'

tasks:
    init:
        dir: enforcer/recipe-rules-basic
        cmds:
          - task: 'tf:init'
          - task: 'tf:plan-vars'
            vars:
                TF_VARS_FILE: config/fixtures_simple.tfvars

