output "configuration_set" {
  value = var.config
  description = "Configuration passed by the consumer of this module"
}

output "output_context"{
  value = local.output_context
  description = "Includes tags generated, and context-metadata"
}

output "tags"{
  value = local.output_context.tags
  description = "Tags generated by the module"
}

output "metadata"{
  value = local.output_context.metadata
  description = "Metadata generated by the module"
}
