---
version: '3'

vars:
    ENVIRONMENT: dev
    AWS_REGION: us-east-1

tasks:
    clean:
        cmds:
            - rm -rf .terraform
            - rm terraform.tfstate || true
            - rm terraform.tfstate.backup || true
            - rm .terraform.lock.hcl || true
            - rm -rf .terragrunt-cache || true
            - rm terraform.tfplan || true

    init:
        deps: [clean]
        cmds:
            - terraform init -backend=false {{ .CLI_ARGS }}

    check:
        deps: [init]
        cmds:
            - terraform validate {{ .CLI_ARGS }}
            - tflint --init
            - tflint .

    # Workaround, to test this module, and execute a successful 'terraform plan' from this module, directly.
    gen-provider:
        cmds:
            - |
              cat <<EOF > providers.tf
              provider "aws" {
                region = var.aws_region
                profile = "bolt-dev"
              }
              EOF

    plan:
        deps: [check, gen-provider]
        cmds:
            - |
              terraform plan -var="tags={\"Environment\":\"{{.ENVIRONMENT}}\"}" \
                -var="aws_region={{.AWS_REGION}}" \
                -var="environment={{.ENVIRONMENT}}" \
                -out=terraform.tfplan \
                {{ .CLI_ARGS }}

            - rm providers.tf || true

    apply:
        deps: [gen-provider]
        cmds:
            - terraform init -backend=false {{ .CLI_ARGS }}
            - |
              terraform apply -var="tags={\"Environment\":\"{{.ENVIRONMENT}}\"}" \
                -var="aws_region={{.AWS_REGION}}" \
                -var="environment={{.ENVIRONMENT}}" \
                -auto-approve \
                {{ .CLI_ARGS }}

            - rm providers.tf || true

    destroy:
        deps: [gen-provider]
        cmds:
            - terraform init -backend=false {{ .CLI_ARGS }}
            - |
              terraform destroy -var="tags={\"Environment\":\"{{.ENVIRONMENT}}\"}" \
                -var="aws_region={{.AWS_REGION}}" \
                -var="environment={{.ENVIRONMENT}}" \
                -auto-approve \
                {{ .CLI_ARGS }}

            - rm providers.tf || true
