---
# TODO: Discuss how to approach this configuration, hopefully file-based.
formatter: markdown table

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
